Network:
  epochs: 300
  batch_size: 65 #250
  n_steps: 16 # timestep
  dataset: "hole"
  in_channels: 1
  data_path: "./data"
  lr: 0.1
  weight_decay: 0.00001
  latent_dim: 128
  input_size: 64
  model: "FSVAE_large" # FSVAE or  FSVAE_large
  k: 20 # multiplier of channel
  scheduled: true # whether to apply scheduled sampling
  loss_func: 'mmd' # mmd or kld


  
