from gym_env.envs.PegInHole_CIC_env import PegInHole
from gym_env.envs.PegInHole_CIC_env_rand import PegInHoleRandom
from gym_env.envs.PegInHole_CIC_env_rand_events import PegInHoleRandomEvents
from gym_env.envs.PegInHole_CIC_env_rand_events_depth import PegInHoleRandomEventsDepth
from gym_env.envs.PegInHole_CIC_env_rand_events_depth_activity_center import PegInHoleRandomEventsDepthActivityCenter
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing import PegInHoleRandomEventsVisualServoing
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding import PegInHoleRandomEventsVisualServoingGuiding
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_2 import PegInHoleRandomEventsVisualServoingGuiding2
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_2_no_coord import PegInHoleRandomEventsVisualServoingGuiding2NC
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_2_rand import PegInHoleRandomEventsVisualServoingGuiding2Rand
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_2_no_coord_rand import PegInHoleRandomEventsVisualServoingGuiding2NCRand


from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_activity import PegInHoleRandomEventsVisualServoingGuidingActivity
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_activity_2 import PegInHoleRandomEventsVisualServoingGuidingActivity2
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_activity_2_no_coord import PegInHoleRandomEventsVisualServoingGuidingActivity2NC
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_activity_2_rand import PegInHoleRandomEventsVisualServoingGuidingActivity2Rand
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_activity_2_no_coord_rand import PegInHoleRandomEventsVisualServoingGuidingActivity2NCRand


from gym_env.envs.PegInHole_CIC_env_test import PegInHole_test
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_corner_activity import PegInHoleRandomEventsVisualServoingGuidingCornerActivity
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_corner_activity_2 import PegInHoleRandomEventsVisualServoingGuidingCornerActivity2
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_corner_activity_2_no_coord import PegInHoleRandomEventsVisualServoingGuidingCornerActivity2NC
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_corner_activity_2_rand import PegInHoleRandomEventsVisualServoingGuidingCornerActivity2Rand
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_corner_activity_2_no_coord_rand import PegInHoleRandomEventsVisualServoingGuidingCornerActivity2NCRand

from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_vae import PegInHoleRandomEventsVisualServoingGuidingVAE
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_vae_2 import PegInHoleRandomEventsVisualServoingGuidingVAE2
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_vae_2_no_coord import PegInHoleRandomEventsVisualServoingGuidingVAE2NC
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_vae_2_rand import PegInHoleRandomEventsVisualServoingGuidingVAE2Rand
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_vae_2_no_coord_rand import PegInHoleRandomEventsVisualServoingGuidingVAE2NCRand



