from gym_env.envs.PegInHole_CIC_env import PegInHole
from gym_env.envs.PegInHole_CIC_env_rand import PegInHoleRandom
from gym_env.envs.PegInHole_CIC_env_rand_events import PegInHoleRandomEvents
from gym_env.envs.PegInHole_CIC_env_rand_events_depth import PegInHoleRandomEventsDepth
from gym_env.envs.PegInHole_CIC_env_rand_events_depth_activity_center import PegInHoleRandomEventsDepthActivityCenter
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing import PegInHoleRandomEventsVisualServoing
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding import PegInHoleRandomEventsVisualServoingGuiding
from gym_env.envs.PegInHole_CIC_env_rand_events_visual_servoing_guiding_activity import PegInHoleRandomEventsVisualServoingGuidingActivity
from gym_env.envs.PegInHole_CIC_env_test import PegInHole_test


